added container checking if server is up

diff --git a/.github/workflows/deploy-preview.yml b/.github/workflows/deploy-preview.yml
--- a/.github/workflows/deploy-preview.yml
+++ b/.github/workflows/deploy-preview.yml
@@ -61,11 +61,11 @@ jobs:
           username: deployuser
           key: ${{ secrets.SSH_KEY }}
           script: |
-            if docker ps --filter "name=pr-preview-${{ github.event.issue.number }}" | grep -q pr-preview; then
+            if docker ps --filter "name=pr-preview-${{ github.event.issue.number }}" | grep -q pr-preview-run; then
               echo "false" > /tmp/container_status.txt
               exit 0
             fi
-            if docker ps --filter "name=pr-preview" | grep -q pr-preview; then
+            if docker ps --filter "name=pr-preview" | grep -q pr-preview-run; then
               echo "true" > /tmp/container_status.txt
               exit 0
             fi
@@ -78,10 +78,20 @@ jobs:
             fi
             docker wait $BUILD_CONTAINER_ID
             docker-compose -f docker-compose-preview.yml up -d --remove-orphans pr-preview-run
+
+            CONTAINER_ID=$(docker-compose -f docker-compose-preview.yml ps -q pr-preview-run)
+            if [ -z "$CONTAINER_ID" ]; then
+              echo "Error: Failed to get container ID for pr-preview-run."
+              exit 1
+            fi
+
             MAX_WAIT=180
             INTERVAL=5
             ELAPSED=0
-            while ! docker-compose -f docker-compose-preview.yml logs | grep -q "Server listening on  { address: '0.0.0.0', family: 'IPv4', port: 3000 }"; do
+
+            START_TIME=$(date +"%Y-%m-%dT%H:%M:%SZ")
+
+            while ! docker logs --since "$START_TIME" "$CONTAINER_ID" 2>&1 | grep -q "Server listening on  { address: '0.0.0.0', family: 'IPv4', port: 3000 }"; do
               if [ $ELAPSED -ge $MAX_WAIT ]; then
                 echo "Max wait time exceeded. Exiting..."
                 exit 1
