add staging compose file

diff --git a/.github/workflows/deploy-staging.yml b/.github/workflows/deploy-staging.yml
--- a/.github/workflows/deploy-staging.yml
+++ b/.github/workflows/deploy-staging.yml
@@ -117,6 +117,7 @@ jobs:
           chmod 600 /tmp/ssh_key.pem
           scp -o StrictHostKeyChecking=no -i /tmp/ssh_key.pem release-artifacts.zip ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.STAGING_PATH }}
 
+      # At some point replace docker-compose-staging.yml with docker-compose-server.yml, see the comments in the docker-compose-staging.yml file 
       - name: Deploy to server
         uses: appleboy/ssh-action@v1.0.3
         with:
@@ -151,28 +152,28 @@ jobs:
             echo 'VITE_APP_URL=${{ vars.WEBSITE_URL }}' > ./app/.env
             echo 'VITE_SERVER_URL=${{ vars.WEBSITE_URL }}' >> ./app/.env
 
-            if [ ! -f "docker-compose-server.yml" ]; then
-              echo "Error: docker-compose-server.yml not found"
+            if [ ! -f "docker-compose-staging.yml" ]; then
+              echo "Error: docker-compose-staging.yml not found"
               exit 1
             fi
 
-            if ! docker-compose -f docker-compose-server.yml ps | grep -q "Up"; then
+            if ! docker-compose -f docker-compose-staging.yml ps | grep -q "Up"; then
               echo "Container is not running. Bringing up the container..."
-              docker-compose -f docker-compose-server.yml up -d
+              docker-compose -f docker-compose-staging.yml up -d
               if [ $? -ne 0 ]; then
                 echo "Error: Failed to bring up the container."
                 exit 1
               fi
             else
               echo "Container is already running. Restarting..."
-              docker-compose -f docker-compose-server.yml restart
+              docker-compose -f docker-compose-staging.yml restart
             fi
 
             START_TIME=$(date +"%Y-%m-%dT%H:%M:%SZ")
 
             sleep 5
 
-            CONTAINER_ID=$(docker-compose -f docker-compose-server.yml ps -q)
+            CONTAINER_ID=$(docker-compose -f docker-compose-staging.yml ps -q)
             if [ -z "$CONTAINER_ID" ]; then
               echo "Error: Failed to get container ID for tsconline."
               exit 1
@@ -186,8 +187,8 @@ jobs:
               if [ $ELAPSED -ge $MAX_WAIT ]; then
                 echo "Max wait time exceeded. Exiting..."
                 echo "Last 200 lines in container:"
-                docker-compose -f docker-compose-server.yml logs --tail=200
-                docker-compose -f docker-compose-server.yml down
+                docker-compose -f docker-compose-staging.yml logs --tail=200
+                docker-compose -f docker-compose-staging.yml down
                 exit 1
               fi
               echo "Waiting for server to start... (elapsed: ${ELAPSED}s)"
