changed release script and added back final deploy step

diff --git a/.github/workflows/deploy-dev.yml b/.github/workflows/deploy-dev.yml
--- a/.github/workflows/deploy-dev.yml
+++ b/.github/workflows/deploy-dev.yml
@@ -5,7 +5,7 @@ concurrency:
 on:
   push:
     branches:
-      - TSC-577-send-artifacts-to-the-server-instead-of-deployments
+      - main
 
 jobs:
   deploy:
@@ -162,87 +162,87 @@ jobs:
           chmod 600 /tmp/ssh_key.pem
           scp -o StrictHostKeyChecking=no -i /tmp/ssh_key.pem $FILES_TO_SEND ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.DEV_PATH }}
 
-      # - name: Deploy to server
-      #   uses: appleboy/ssh-action@v1.0.3
-      #   with:
-      #     host: ${{ secrets.SSH_HOST }}
-      #     username: ${{ secrets.SSH_USERNAME }}
-      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
-      #     script: |
-      #       cd ${{ secrets.DEV_PATH }}
+      - name: Deploy to server
+        uses: appleboy/ssh-action@v1.0.3
+        with:
+          host: ${{ secrets.SSH_HOST }}
+          username: ${{ secrets.SSH_USERNAME }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          script: |
+            cd ${{ secrets.DEV_PATH }}
 
-      #       git pull --no-edit
+            git pull --no-edit
 
-      #       PULL_STATUS=$?
+            PULL_STATUS=$?
 
-      #       if [ $PULL_STATUS -eq 0 ]; then
-      #         echo "git pull succeeded"
-      #       else
-      #         echo "git pull failed with exit status $PULL_STATUS"
-      #         echo "General error: Possible reasons could include merge conflicts, network issues, or authentication problems."
-      #         exit 1
-      #       fi
+            if [ $PULL_STATUS -eq 0 ]; then
+              echo "git pull succeeded"
+            else
+              echo "git pull failed with exit status $PULL_STATUS"
+              echo "General error: Possible reasons could include merge conflicts, network issues, or authentication problems."
+              exit 1
+            fi
 
-      #       unzip -o build-artifacts.zip -d ${{ secrets.DEV_PATH }}
-      #       rm build-artifacts.zip
-      #       if [ -f "${{ steps.check_active_jar.outputs.new_active_jar }}" ]; then
-      #         mv ${{ steps.check_active_jar.outputs.new_active_jar }} ${{ secrets.DEV_PATH }}/server/assets/jars
-      #       fi
+            unzip -q -o build-artifacts.zip -d ${{ secrets.DEV_PATH }}
+            rm build-artifacts.zip
+            if [ -f "${{ steps.check_active_jar.outputs.new_active_jar }}" ]; then
+              mv ${{ steps.check_active_jar.outputs.new_active_jar }} ${{ secrets.DEV_PATH }}/server/assets/jars
+            fi
 
-      #       echo 'EMAIL_USER="${{ secrets.EMAIL_USER }}"' > ./server/.env
-      #       echo 'EMAIL_PASS="${{ secrets.EMAIL_PASS }}"' >> ./server/.env
-      #       echo 'SESSION_KEY="${{ secrets.SESSION_KEY }}"' >> ./server/.env
-      #       echo 'NODE_ENV="production"' >> ./server/.env
-      #       echo 'RECAPTCHA_SECRET_KEY="${{ secrets.RECAPTCHA_SECRET_KEY }}"' >> ./server/.env
-      #       echo 'APP_URL="${{ vars.WEBSITE_URL }}"' >> ./server/.env
-      #       echo 'ADMIN_USER="${{ secrets.ADMIN_USER }}"' >> ./server/.env
-      #       echo 'ADMIN_PASS="${{ secrets.ADMIN_PASS }}"' >> ./server/.env
-      #       echo 'ADMIN_EMAIL="${{ secrets.ADMIN_EMAIL }}"' >> ./server/.env
-      #       echo 'DOMAIN="dev.timescalecreator.org"' >> ./server/.env
+            echo 'EMAIL_USER="${{ secrets.EMAIL_USER }}"' > ./server/.env
+            echo 'EMAIL_PASS="${{ secrets.EMAIL_PASS }}"' >> ./server/.env
+            echo 'SESSION_KEY="${{ secrets.SESSION_KEY }}"' >> ./server/.env
+            echo 'NODE_ENV="production"' >> ./server/.env
+            echo 'RECAPTCHA_SECRET_KEY="${{ secrets.RECAPTCHA_SECRET_KEY }}"' >> ./server/.env
+            echo 'APP_URL="${{ vars.WEBSITE_URL }}"' >> ./server/.env
+            echo 'ADMIN_USER="${{ secrets.ADMIN_USER }}"' >> ./server/.env
+            echo 'ADMIN_PASS="${{ secrets.ADMIN_PASS }}"' >> ./server/.env
+            echo 'ADMIN_EMAIL="${{ secrets.ADMIN_EMAIL }}"' >> ./server/.env
+            echo 'DOMAIN="dev.timescalecreator.org"' >> ./server/.env
 
-      #       echo 'VITE_APP_URL=${{ vars.WEBSITE_URL }}' > ./app/.env
-      #       echo 'VITE_SERVER_URL=${{ vars.WEBSITE_URL }}' >> ./app/.env
+            echo 'VITE_APP_URL=${{ vars.WEBSITE_URL }}' > ./app/.env
+            echo 'VITE_SERVER_URL=${{ vars.WEBSITE_URL }}' >> ./app/.env
 
-      #       if [ ! -f "docker-compose-server.yml" ]; then
-      #         echo "Error: docker-compose-server.yml not found"
-      #         exit 1
-      #       fi
+            if [ ! -f "docker-compose-server.yml" ]; then
+              echo "Error: docker-compose-server.yml not found"
+              exit 1
+            fi
 
-      #       CONTAINER_ID=$(docker ps --filter "name=tsconline" --format "{{.ID}}")
-      #       if [ -z "$CONTAINER_ID" ]; then
-      #         echo "Container is not running. Bringing up the container..."
-      #         docker-compose -f docker-compose-server.yml up -d
-      #         if [ $? -ne 0 ]; then
-      #           echo "Error: Failed to bring up the container."
-      #           exit 1
-      #         fi
-      #       else
-      #         echo "Container is already running. Restarting..."
-      #         docker-compose -f docker-compose-server.yml restart
-      #       fi
+            CONTAINER_ID=$(docker ps --filter "name=tsconline" --format "{{.ID}}")
+            if [ -z "$CONTAINER_ID" ]; then
+              echo "Container is not running. Bringing up the container..."
+              docker-compose -f docker-compose-server.yml up -d
+              if [ $? -ne 0 ]; then
+                echo "Error: Failed to bring up the container."
+                exit 1
+              fi
+            else
+              echo "Container is already running. Restarting..."
+              docker-compose -f docker-compose-server.yml restart
+            fi
 
-      #       START_TIME=$(date +"%Y-%m-%dT%H:%M:%SZ")
-      #       sleep 5
+            START_TIME=$(date +"%Y-%m-%dT%H:%M:%SZ")
+            sleep 5
 
-      #       CONTAINER_ID=$(docker ps --filter "name=tsconline" --format "{{.ID}}")
-      #       if [ -z "$CONTAINER_ID" ]; then
-      #         echo "Error: Failed to get container ID for tsconline."
-      #         exit 1
-      #       fi
+            CONTAINER_ID=$(docker ps --filter "name=tsconline" --format "{{.ID}}")
+            if [ -z "$CONTAINER_ID" ]; then
+              echo "Error: Failed to get container ID for tsconline."
+              exit 1
+            fi
 
-      #       MAX_WAIT=480
-      #       INTERVAL=5
-      #       ELAPSED=0
+            MAX_WAIT=480
+            INTERVAL=5
+            ELAPSED=0
 
-      #       while ! docker logs --since "$START_TIME" "$CONTAINER_ID" 2>&1 | grep -q "Server listening on  { address: '0.0.0.0', family: 'IPv4', port: 3000 }"; do
-      #         if [ $ELAPSED -ge $MAX_WAIT ]; then
-      #           echo "Max wait time exceeded. Exiting..."
-      #           echo "Last 200 lines in container:"
-      #           docker-compose -f docker-compose-server.yml logs --tail=200
-      #           docker-compose -f docker-compose-server.yml stop
-      #           exit 1
-      #         fi
-      #         echo "Waiting for server to start... (elapsed: ${ELAPSED}s)"
-      #         sleep $INTERVAL
-      #         ELAPSED=$((ELAPSED + INTERVAL))
-      #       done
+            while ! docker logs --since "$START_TIME" "$CONTAINER_ID" 2>&1 | grep -q "Server listening on  { address: '0.0.0.0', family: 'IPv4', port: 3000 }"; do
+              if [ $ELAPSED -ge $MAX_WAIT ]; then
+                echo "Max wait time exceeded. Exiting..."
+                echo "Last 200 lines in container:"
+                docker-compose -f docker-compose-server.yml logs --tail=200
+                docker-compose -f docker-compose-server.yml stop
+                exit 1
+              fi
+              echo "Waiting for server to start... (elapsed: ${ELAPSED}s)"
+              sleep $INTERVAL
+              ELAPSED=$((ELAPSED + INTERVAL))
+            done
