extra checking for confirm-deploy

diff --git a/.github/workflows/deploy-preview.yml b/.github/workflows/deploy-preview.yml
--- a/.github/workflows/deploy-preview.yml
+++ b/.github/workflows/deploy-preview.yml
@@ -183,14 +183,25 @@ jobs:
             cd /home/aaron/tsconline/pr-preview-${{ github.event.issue.number }}
             docker ps --filter "name=pr-preview" --format "{{.Names}}" | grep -oP "pr-preview-\K[0-9]+" > /tmp/running_pr.txt
             RUNNING_CONTAINER=$(docker ps --filter "name=pr-preview" --format "{{.ID}}")
-            echo "Stopping and removing container $RUNNING_CONTAINER"
-            docker stop $RUNNING_CONTAINER
-            docker rm $RUNNING_CONTAINER
+            if [ -n "$RUNNING_CONTAINER" ]; then
+              echo "Stopping and removing container $RUNNING_CONTAINER"
+              docker stop $RUNNING_CONTAINER
+              docker rm $RUNNING_CONTAINER
+            fi 
             docker-compose -f docker-compose-preview.yml up -d --remove-orphans pr-preview-run
+            CONTAINER_ID=$(docker-compose -f docker-compose-preview.yml ps -q pr-preview-run)
+            if [ -z "$CONTAINER_ID" ]; then
+              echo "Error: Failed to get container ID for pr-preview-run."
+              exit 1
+            fi
+
+            START_TIME=$(date +"%Y-%m-%dT%H:%M:%SZ")
+
             MAX_WAIT=180
             INTERVAL=5
             ELAPSED=0
-            while ! docker-compose -f docker-compose-preview.yml logs | grep -q "Server listening on  { address: '0.0.0.0', family: 'IPv4', port: 3000 }"; do
+
+            while ! docker logs --since "$START_TIME" "$CONTAINER_ID" 2>&1 | grep -q "Server listening on  { address: '0.0.0.0', family: 'IPv4', port: 3000 }"; do
               if [ $ELAPSED -ge $MAX_WAIT ]; then
                 echo "Max wait time exceeded. Exiting..."
                 exit 1
