added pull checks

diff --git a/.github/workflows/deploy-release.yml b/.github/workflows/deploy-release.yml
--- a/.github/workflows/deploy-release.yml
+++ b/.github/workflows/deploy-release.yml
@@ -38,6 +38,14 @@ jobs:
 
             git pull --no-edit
 
+            if [ $PULL_STATUS -eq 0 ]; then
+              echo "git pull succeeded"
+            else
+              echo "git pull failed with exit status $PULL_STATUS"
+              echo "General error: Possible reasons could include merge conflicts, network issues, or authentication problems."
+              exit 1
+            fi
+
             echo 'EMAIL_USER="${{ secrets.EMAIL_USER }}"' > ./server/.env
             echo 'EMAIL_PASS="${{ secrets.EMAIL_PASS }}"' >> ./server/.env
             echo 'SESSION_KEY="${{ secrets.SESSION_KEY }}"' >> ./server/.env
