full pipeline

diff --git a/.github/workflows/merge-pipeline.yml b/.github/workflows/merge-pipeline.yml
--- a/.github/workflows/merge-pipeline.yml
+++ b/.github/workflows/merge-pipeline.yml
@@ -208,24 +208,24 @@ jobs:
           ACCESS_TOKEN=$(curl -s https://api.dropbox.com/oauth2/token -d refresh_token=${{ secrets.DROPBOX_REFRESH_TOKEN }} -d grant_type=refresh_token -d client_id=${{ secrets.DROPBOX_APP_KEY }} -d client_secret=${{ secrets.DROPBOX_APP_SECRET }} | jq -r '.access_token')
 
           DECRYPTION_NAME=$(jq -r '.decryptionJar' server/assets/config.json | xargs basename)
-          echo "name=$DECRYPTION_NAME" >> $GITHUB_OUTPUT
-          echo "Decryption Jar: $DECRYPTION_NAME"
+          if [ -z "$DECRYPTION_NAME" ]; then
+            echo "Error: decryptionJar not found in config.json"
+            exit 1
+          fi
 
           DROPBOX_FOLDER_PATH="${{ secrets.DROPBOX_PATH }}"
           LIST_RESPONSE=$(curl -s -X POST "https://api.dropboxapi.com/2/files/list_folder" \
           --header "Authorization: Bearer $ACCESS_TOKEN" \
           --header "Content-Type: application/json" \
           --data "{\"path\": \"$DROPBOX_FOLDER_PATH\"}")
-          echo "Contents of Dropbox folder:"
-          echo "$LIST_RESPONSE"
-          
+
           DECRYPTION_PATH=$(echo "$LIST_RESPONSE" | jq -r --arg DECRYPTION_NAME "$DECRYPTION_NAME" '.entries[] | select(.name == $DECRYPTION_NAME) | .path_lower')
           echo "Decryption JAR path: $DECRYPTION_PATH"
           if [ -z "$DECRYPTION_PATH" ]; then
             echo "Error: Decryption jar not found."
-          exit 1
+            exit 1
           fi
-  
+
           curl -s -X POST "https://content.dropboxapi.com/2/files/download" \
           --header "Authorization: Bearer $ACCESS_TOKEN" \
           --header "Dropbox-API-Arg: {\"path\": \"$DECRYPTION_PATH\"}" \
@@ -236,9 +236,10 @@ jobs:
             echo "Error: Failed to download decryption jar."
             exit 1
           fi
-
-          echo "Decryption jar downloaded successfully: $DECRYPTION_JAR"
-          echo "jar_path=$DECRYPTION_JAR" >> $GITHUB_OUTPUT
+          else
+            echo "Successfully downloaded decryption jar."
+            echo "jar_path=$DECRYPTION_JAR" >> $GITHUB_OUTPUT
+          fi
 
       - name: Run Tests
         id: run_tests
@@ -259,9 +260,13 @@ jobs:
           echo "Active JAR: $pr_jar"
 
           DECRYPTION_JAR="${{ steps.decrypt_step.outputs.jar_path }}"
-          echo "Decryption JAR: $DECRYPTION_JAR"
+          if [ -z "$DECRYPTION_JAR" ]; then
+            echo "Error: Decryption jar path not found."
+            exit 1
+          fi
 
           mv ${{ github.workspace }}/server/assets/jars/testUsageJar.jar ${{ github.workspace }}/server/assets/jars/$pr_jar
+
           if [ ! -f "$DECRYPTION_JAR" ]; then
             echo "Decryption jar not found. Moving it to the required location."
             mv $DECRYPTION_JAR ${{ github.workspace }}/server/assets/jars/
@@ -274,6 +279,7 @@ jobs:
           yarn coverage:ci > test_output.log 2>&1 || (grep -q 'ERROR: Coverage' test_output.log && echo "coverage_failed=true" >> $GITHUB_OUTPUT) || echo "test_failed=true" >> $GITHUB_OUTPUT
 
           mv ${{ github.workspace }}/server/assets/jars/$pr_jar ${{ github.workspace }}/server/assets/jars/testUsageJar.jar
+
           echo "Renamed jar back to testUsageJar.jar"
           if [ -f "${{ github.workspace }}/server/assets/jars/testUsageJar.jar" ]; then
             echo "Successfully renamed jar back to testUsageJar.jar."
