decryption

diff --git a/.github/workflows/merge-pipeline.yml b/.github/workflows/merge-pipeline.yml
--- a/.github/workflows/merge-pipeline.yml
+++ b/.github/workflows/merge-pipeline.yml
@@ -202,13 +202,13 @@ jobs:
             exit 1
           fi
 
-      - name: Build decryption Jar
+      - name: Find and Download Decryption Jar from Dropbox
         run: |
           ACCESS_TOKEN=$(curl -s https://api.dropbox.com/oauth2/token -d refresh_token=${{ secrets.DROPBOX_REFRESH_TOKEN }} -d grant_type=refresh_token -d client_id=${{ secrets.DROPBOX_APP_KEY }} -d client_secret=${{ secrets.DROPBOX_APP_SECRET }} | jq -r '.access_token')
 
-          JAR_NAME=$(jq -r '.decryptionJar' server/assets/config.json | xargs basename)
-          echo "name=$JAR_NAME" >> $GITHUB_OUTPUT
-          echo "Decryption Jar: $JAR_NAME"
+          DECRYPTION_NAME=$(jq -r '.decryptionJar' server/assets/config.json | xargs basename)
+          echo "name=$DECRYPTION_NAME" >> $GITHUB_OUTPUT
+          echo "Decryption Jar: $DECRYPTION_NAME"
 
           DROPBOX_FOLDER_PATH="${{ secrets.DROPBOX_PATH }}"
           LIST_RESPONSE=$(curl -s -X POST "https://api.dropboxapi.com/2/files/list_folder" \
@@ -218,12 +218,24 @@ jobs:
           echo "Contents of Dropbox folder:"
           echo "$LIST_RESPONSE"
           
-            DECRYPTION_JAR=$(echo "$LIST_RESPONSE" | jq -r --arg JAR_NAME "$JAR_NAME" '.entries[] | select(.name == $JAR_NAME) | .path_lower')
-          echo "Decryption JAR path: $DECRYPTION_JAR"
-          if [ -z "$DECRYPTION_JAR" ]; then
+          DECRYPTION_PATH=$(echo "$LIST_RESPONSE" | jq -r --arg DECRYPTION_NAME "$DECRYPTION_NAME" '.entries[] | select(.name == $DECRYPTION_NAME) | .path_lower')
+          echo "Decryption JAR path: $DECRYPTION_PATH"
+          if [ -z "$DECRYPTION_PATH" ]; then
             echo "Error: Decryption jar not found."
+          exit 1
+          fi
+  
+          curl -s -X POST "https://content.dropboxapi.com/2/files/download" \
+          --header "Authorization: Bearer $ACCESS_TOKEN" \
+          --header "Dropbox-API-Arg: {\"path\": \"$DECRYPTION_PATH\"}" \
+          --output "$DECRYPTION_JAR"
+
+          if [ ! -f "$DECRYPTION_JAR" ]; then
+            echo "Error: Failed to download decryption jar."
             exit 1
           fi
+
+          echo "Decryption jar downloaded successfully: $DECRYPTION_JAR"
 
       - name: Run Tests
         id: run_tests
@@ -245,6 +257,12 @@ jobs:
           echo "Decryption JAR: $DECRYPTION_JAR"
 
           mv ${{ github.workspace }}/server/assets/jars/testUsageJar.jar ${{ github.workspace }}/server/assets/jars/$pr_jar
+          if [ ! -f "$DECRYPTION_JAR" ]; then
+            echo "Decryption jar not found. Moving it to the required location."
+            mv ${{ github.workspace }}/server/assets/jars/$DECRYPTION_JAR ${{ github.workspace }}/server/assets/jars/
+          else
+            echo "Decryption jar already in the required location."
+          fi
           echo "Renamed jar to $pr_jar"
 
           Xvfb :1 -screen 0 1024x768x16 &
@@ -259,8 +277,6 @@ jobs:
             echo "Failed to rename jar back to testUsageJar.jar."
             exit 1
           fi
-
-        continue-on-error: true
 
       - name: Run Tests and Coverage (Exclude Encryption)
         id: run_tests_exclude_encryption
