decryption jar

diff --git a/.github/workflows/merge-pipeline.yml b/.github/workflows/merge-pipeline.yml
--- a/.github/workflows/merge-pipeline.yml
+++ b/.github/workflows/merge-pipeline.yml
@@ -202,6 +202,24 @@ jobs:
             exit 1
           fi
 
+      - name: Build decryption Jar
+        run: |
+          ACCESS_TOKEN=$(curl -s https://api.dropbox.com/oauth2/token -d refresh_token=${{ secrets.DROPBOX_REFRESH_TOKEN }} -d grant_type=refresh_token -d client_id=${{ secrets.DROPBOX_APP_KEY }} -d client_secret=${{ secrets.DROPBOX_APP_SECRET }} | jq -r '.access_token')
+
+          LIST_PAYLOAD=$(printf '{"path": "%s", "recursive": false}' "${{ secrets.DROPBOX_PATH }}")
+          LIST_RESPONSE=$(curl -s -X POST https://api.dropboxapi.com/2/files/list_folder \
+            --header "Authorization: Bearer $ACCESS_TOKEN" \
+            --header "Content-Type: application/json" \
+            --data "$LIST_PAYLOAD")
+          echo "List Folder Response: $LIST_RESPONSE"
+          
+          DECRYPTION_JAR=$(echo "$LIST_RESPONSE" | jq -r '.entries[] | select(.name | test("decryption-.*\\.jar$")) | .path_lower')
+          echo "Decryption JAR path: $DECRYPTION_JAR"
+          if [ -z "$DECRYPTION_JAR" ]; then
+            echo "Error: Decryption jar not found."
+            exit 1
+          fi
+
       - name: Run Tests
         id: run_tests
         if: github.event.pull_request.user.login != 'dependabot[bot]'
@@ -219,6 +237,7 @@ jobs:
             exit 1
           fi
           echo "Active JAR: $pr_jar"
+          echo "Decryption JAR: $DECRYPTION_JAR"
 
           mv ${{ github.workspace }}/server/assets/jars/testUsageJar.jar ${{ github.workspace }}/server/assets/jars/$pr_jar
           echo "Renamed jar to $pr_jar"
@@ -227,7 +246,7 @@ jobs:
           export DISPLAY=:1
           yarn coverage:ci > test_output.log 2>&1 || (grep -q 'ERROR: Coverage' test_output.log && echo "coverage_failed=true" >> $GITHUB_OUTPUT) || echo "test_failed=true" >> $GITHUB_OUTPUT
 
-          mv ${{ github.workspace }}/server/assets/jars/$CONFIG_JAR_NAME ${{ github.workspace }}/server/assets/jars/testUsageJar.jar
+          mv ${{ github.workspace }}/server/assets/jars/$pr_jar ${{ github.workspace }}/server/assets/jars/testUsageJar.jar
           echo "Renamed jar back to testUsageJar.jar"
           if [ -f "${{ github.workspace }}/server/assets/jars/testUsageJar.jar" ]; then
             echo "Successfully renamed jar back to testUsageJar.jar."
