final e2e testing

diff --git a/.github/workflows/merge-pipeline.yml b/.github/workflows/merge-pipeline.yml
--- a/.github/workflows/merge-pipeline.yml
+++ b/.github/workflows/merge-pipeline.yml
@@ -225,17 +225,17 @@ jobs:
         id: run_tests
         if: github.event.pull_request.user.login != 'dependabot[bot]'
         run: |
-          # Xvfb :1 -screen 0 1024x768x16 &
-          # export DISPLAY=:1
-          # yarn coverage:ci > test_output.log 2>&1 || (grep -q 'ERROR: Coverage' test_output.log && echo "coverage_failed=true" >> $GITHUB_OUTPUT) || echo "test_failed=true" >> $GITHUB_OUTPUT
+          Xvfb :1 -screen 0 1024x768x16 &
+          export DISPLAY=:1
+          yarn coverage:ci > test_output.log 2>&1 || (grep -q 'ERROR: Coverage' test_output.log && echo "coverage_failed=true" >> $GITHUB_OUTPUT) || echo "test_failed=true" >> $GITHUB_OUTPUT
 
       - name: Run Tests and Coverage (Exclude Encryption)
         id: run_tests_exclude_encryption
         if: github.event.pull_request.user.login == 'dependabot[bot]'
         run: |
-          # Xvfb :1 -screen 0 1024x768x16 &
-          # export DISPLAY=:1
-          # yarn coverage:ci:exclude-encryption > test_output.log 2>&1 || (grep -q 'ERROR: Coverage' test_output.log && echo "coverage_failed=true" >> $GITHUB_OUTPUT) || echo "test_failed=true" >> $GITHUB_OUTPUT
+          Xvfb :1 -screen 0 1024x768x16 &
+          export DISPLAY=:1
+          yarn coverage:ci:exclude-encryption > test_output.log 2>&1 || (grep -q 'ERROR: Coverage' test_output.log && echo "coverage_failed=true" >> $GITHUB_OUTPUT) || echo "test_failed=true" >> $GITHUB_OUTPUT
         continue-on-error: true
 
       - name: Post Coverage Comment
@@ -244,28 +244,28 @@ jobs:
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
-            # const fs = require('fs');
-            # const log = fs.readFileSync('test_output.log', 'utf8');
-            # const coverageErrors = log.split('\n').filter(line => line.includes('ERROR: Coverage'));
+            const fs = require('fs');
+            const log = fs.readFileSync('test_output.log', 'utf8');
+            const coverageErrors = log.split('\n').filter(line => line.includes('ERROR: Coverage'));
 
-            # const commentBody = `
-            # ## :x: Coverage Thresholds Not Met
+            const commentBody = `
+            ## :x: Coverage Thresholds Not Met
 
-            # The following coverage thresholds were not met:
+            The following coverage thresholds were not met:
 
-            # \`\`\`
-            # ${coverageErrors.join('\n')}
-            # \`\`\`
+            \`\`\`
+            ${coverageErrors.join('\n')}
+            \`\`\`
 
-            # Please review the coverage report and improve the tests to meet the thresholds.
-            # `;
+            Please review the coverage report and improve the tests to meet the thresholds.
+            `;
 
-            # github.rest.issues.createComment({
-            #   issue_number: context.issue.number,
-            #   owner: context.repo.owner,
-            #   repo: context.repo.repo,
-            #   body: commentBody
-            # });
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: commentBody
+            });
 
       - name: Move TSCreator Jar for e2e
         id: move_jar
@@ -352,9 +352,9 @@ jobs:
         if: github.event.pull_request.user.login != 'dependabot[bot]'
         id: e2e_tests
         run: |
-          # Xvfb :1 -screen 0 1024x768x16 &
-          # export DISPLAY=:1
-          yarn test:charts:ci datapack.test.ts > e2e_output.log 2>&1 || echo "e2e_failed=true" >> $GITHUB_OUTPUT
+          Xvfb :1 -screen 0 1024x768x16 &
+          export DISPLAY=:1
+          yarn test:charts:ci > e2e_output.log 2>&1 || echo "e2e_failed=true" >> $GITHUB_OUTPUT
 
           pr_jar=${{ steps.move_jar.outputs.pr_jar }}
           if [ -z "$pr_jar" ]; then
