readded full merge pipeline

diff --git a/.github/workflows/merge-pipeline.yml b/.github/workflows/merge-pipeline.yml
--- a/.github/workflows/merge-pipeline.yml
+++ b/.github/workflows/merge-pipeline.yml
@@ -161,112 +161,112 @@ jobs:
         if: steps.build.outputs.build_failed == 'true'
         run: exit 1
 
-      # - name: Set up SSH key
-      #   if: github.event.pull_request.user.login != 'dependabot[bot]'
-      #   run: |
-      #     eval $(ssh-agent)
-      #     mkdir -p ~/.ssh
-      #     echo "${{ secrets.JAVA_DEPLOY_KEY }}" > ~/.ssh/id_rsa
-      #     chmod 600 ~/.ssh/id_rsa
-      #     echo -e "Host bitbucket.org\n\tAddKeysToAgent yes\n\tIdentityFile ~/.ssh/id_rsa" > ~/.ssh/config
-      #     ssh-add ~/.ssh/id_rsa
-      #     ssh-keyscan -H bitbucket.org >> ~/.ssh/known_hosts
+      - name: Set up SSH key
+        if: github.event.pull_request.user.login != 'dependabot[bot]'
+        run: |
+          eval $(ssh-agent)
+          mkdir -p ~/.ssh
+          echo "${{ secrets.JAVA_DEPLOY_KEY }}" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
+          echo -e "Host bitbucket.org\n\tAddKeysToAgent yes\n\tIdentityFile ~/.ssh/id_rsa" > ~/.ssh/config
+          ssh-add ~/.ssh/id_rsa
+          ssh-keyscan -H bitbucket.org >> ~/.ssh/known_hosts
 
-      # - name: Checkout code from Bitbucket
-      #   if: github.event.pull_request.user.login != 'dependabot[bot]'
-      #   run: |
-      #     git clone git@bitbucket.org:strat/tscreator.git
+      - name: Checkout code from Bitbucket
+        if: github.event.pull_request.user.login != 'dependabot[bot]'
+        run: |
+          git clone git@bitbucket.org:strat/tscreator.git
 
-      # - name: Set up jdk
-      #   if: github.event.pull_request.user.login != 'dependabot[bot]'
-      #   uses: actions/setup-java@v4
-      #   with:
-      #     distribution: "temurin"
-      #     java-version: "8"
-      #     java-package: "jdk"
+      - name: Set up jdk
+        if: github.event.pull_request.user.login != 'dependabot[bot]'
+        uses: actions/setup-java@v4
+        with:
+          distribution: "temurin"
+          java-version: "8"
+          java-package: "jdk"
 
-      # - name: Build and compile TSCreator Jar for tests
-      #   if: github.event.pull_request.user.login != 'dependabot[bot]'
-      #   run: |
-      #     cd ${{ github.workspace }}/tscreator/devel
-      #     make
-      #     make jar
-      #     find ${{ github.workspace }}/tscreator/jars/ -type f -name '*.jar' -exec cp {} ${{ github.workspace }}/server/assets/jars/testUsageJar.jar \;
-      #     if [ -f "${{ github.workspace }}/server/assets/jars/testUsageJar.jar" ]; then
-      #       echo "Successfully made jar."
-      #     else
-      #       echo "Failed to make jar."
-      #       exit 1
-      #     fi
+      - name: Build and compile TSCreator Jar for tests
+        if: github.event.pull_request.user.login != 'dependabot[bot]'
+        run: |
+          cd ${{ github.workspace }}/tscreator/devel
+          make
+          make jar
+          find ${{ github.workspace }}/tscreator/jars/ -type f -name '*.jar' -exec cp {} ${{ github.workspace }}/server/assets/jars/testUsageJar.jar \;
+          if [ -f "${{ github.workspace }}/server/assets/jars/testUsageJar.jar" ]; then
+            echo "Successfully made jar."
+          else
+            echo "Failed to make jar."
+            exit 1
+          fi
         
-      # - name: Run Tests
-      #   id: run_tests
-      #   if: github.event.pull_request.user.login != 'dependabot[bot]'
-      #   run: |
-      #     Xvfb :1 -screen 0 1024x768x16 &
-      #     export DISPLAY=:1
-      #     yarn coverage:ci > test_output.log 2>&1 || (grep -q 'ERROR: Coverage' test_output.log && echo "coverage_failed=true" >> $GITHUB_OUTPUT) || echo "test_failed=true" >> $GITHUB_OUTPUT
-      #   continue-on-error: true
+      - name: Run Tests
+        id: run_tests
+        if: github.event.pull_request.user.login != 'dependabot[bot]'
+        run: |
+          Xvfb :1 -screen 0 1024x768x16 &
+          export DISPLAY=:1
+          yarn coverage:ci > test_output.log 2>&1 || (grep -q 'ERROR: Coverage' test_output.log && echo "coverage_failed=true" >> $GITHUB_OUTPUT) || echo "test_failed=true" >> $GITHUB_OUTPUT
+        continue-on-error: true
 
-      # - name: Run Tests and Coverage (Exclude Encryption)
-      #   id: run_tests_exclude_encryption
-      #   if: github.event.pull_request.user.login == 'dependabot[bot]'
-      #   run: | 
-      #     Xvfb :1 -screen 0 1024x768x16 &
-      #     export DISPLAY=:1
-      #     yarn coverage:ci:exclude-encryption > test_output.log 2>&1 || (grep -q 'ERROR: Coverage' test_output.log && echo "coverage_failed=true" >> $GITHUB_OUTPUT) || echo "test_failed=true" >> $GITHUB_OUTPUT
-      #   continue-on-error: true
+      - name: Run Tests and Coverage (Exclude Encryption)
+        id: run_tests_exclude_encryption
+        if: github.event.pull_request.user.login == 'dependabot[bot]'
+        run: | 
+          Xvfb :1 -screen 0 1024x768x16 &
+          export DISPLAY=:1
+          yarn coverage:ci:exclude-encryption > test_output.log 2>&1 || (grep -q 'ERROR: Coverage' test_output.log && echo "coverage_failed=true" >> $GITHUB_OUTPUT) || echo "test_failed=true" >> $GITHUB_OUTPUT
+        continue-on-error: true
 
-      # - name: Post Coverage Comment
-      #   if: steps.run_tests.outputs.coverage_failed == 'true'
-      #   uses: actions/github-script@v6
-      #   with:
-      #     github-token: ${{ secrets.GITHUB_TOKEN }}
-      #     script: |
-      #       const fs = require('fs');
-      #       const log = fs.readFileSync('test_output.log', 'utf8');
-      #       const coverageErrors = log.split('\n').filter(line => line.includes('ERROR: Coverage'));
+      - name: Post Coverage Comment
+        if: steps.run_tests.outputs.coverage_failed == 'true'
+        uses: actions/github-script@v6
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const fs = require('fs');
+            const log = fs.readFileSync('test_output.log', 'utf8');
+            const coverageErrors = log.split('\n').filter(line => line.includes('ERROR: Coverage'));
   
-      #       const commentBody = `
-      #       ## :x: Coverage Thresholds Not Met
+            const commentBody = `
+            ## :x: Coverage Thresholds Not Met
   
-      #       The following coverage thresholds were not met:
+            The following coverage thresholds were not met:
             
-      #       \`\`\`
-      #       ${coverageErrors.join('\n')}
-      #       \`\`\`
+            \`\`\`
+            ${coverageErrors.join('\n')}
+            \`\`\`
   
-      #       Please review the coverage report and improve the tests to meet the thresholds.
-      #       `;
+            Please review the coverage report and improve the tests to meet the thresholds.
+            `;
   
-      #       github.rest.issues.createComment({
-      #         issue_number: context.issue.number,
-      #         owner: context.repo.owner,
-      #         repo: context.repo.repo,
-      #         body: commentBody
-      #       });
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: commentBody
+            });
 
-      # - name: Report Test Errors
-      #   if: steps.run_tests.outputs.test_failed == 'true'
-      #   uses: actions/github-script@v5
-      #   with:
-      #     script: |
-      #       const fs = require('fs');
-      #       const testLog = fs.readFileSync('test_output.log', 'utf8');
-      #       const prNumber = context.payload.pull_request?.number;
-      #       if (prNumber) {
-      #         const message = `🚨 Vitest tests have failed. Please check the test logs for more information.\n\n\`\`\`\n${testLog}\n\`\`\``;
-      #         github.rest.issues.createComment({
-      #           ...context.repo,
-      #           issue_number: prNumber,
-      #           body: message,
-      #         });
-      #       }
-      #     github-token: ${{ secrets.GITHUB_TOKEN }}
+      - name: Report Test Errors
+        if: steps.run_tests.outputs.test_failed == 'true'
+        uses: actions/github-script@v5
+        with:
+          script: |
+            const fs = require('fs');
+            const testLog = fs.readFileSync('test_output.log', 'utf8');
+            const prNumber = context.payload.pull_request?.number;
+            if (prNumber) {
+              const message = `🚨 Vitest tests have failed. Please check the test logs for more information.\n\n\`\`\`\n${testLog}\n\`\`\``;
+              github.rest.issues.createComment({
+                ...context.repo,
+                issue_number: prNumber,
+                body: message,
+              });
+            }
+          github-token: ${{ secrets.GITHUB_TOKEN }}
 
-      # - name: Check for any test failures
-      #   if: steps.run_tests.outputs.test_failed == 'true' || steps.run_tests.outputs.coverage_failed == 'true'
-      #   run: exit 1
+      - name: Check for any test failures
+        if: steps.run_tests.outputs.test_failed == 'true' || steps.run_tests.outputs.coverage_failed == 'true'
+        run: exit 1
 
       - name: Parse JAR Names
         id: parse_jar_names
