testing workflow speed

diff --git a/.github/workflows/merge-pipeline.yml b/.github/workflows/merge-pipeline.yml
--- a/.github/workflows/merge-pipeline.yml
+++ b/.github/workflows/merge-pipeline.yml
@@ -196,9 +196,10 @@ jobs:
           Xvfb :1 -screen 0 1024x768x16 &
           export DISPLAY=:1
           set -o pipefail
-          if ! yarn coverage:ci > test_output.log 2>&1; then
-            echo "test_failed=true" >> $GITHUB_OUTPUT
-          fi
+          yarn coverage:ci
+          # if ! yarn coverage:ci > test_output.log 2>&1; then
+          #   echo "test_failed=true" >> $GITHUB_OUTPUT
+          # fi
         continue-on-error: true
 
       - name: Report Test Errors
@@ -258,7 +259,7 @@ jobs:
           base-lcov-file: "./base-lcov.info"
           minimum-ratio: 0 # Fails Github action once code coverage is decreasing
           send-summary-comment: true
-          show-annotations: "warning" # Possible options warning|error
+          show-annotations: "warning"
 
   wait-for-checks:
     runs-on: ubuntu-latest
