fixed package.json

diff --git a/.github/workflows/merge-pipeline.yml b/.github/workflows/merge-pipeline.yml
--- a/.github/workflows/merge-pipeline.yml
+++ b/.github/workflows/merge-pipeline.yml
@@ -237,51 +237,51 @@ jobs:
             exit 1
           fi
 
-      # - name: Run Tests
-      #   id: run_tests
-      #   if: github.event.pull_request.user.login != 'dependabot[bot]'
-      #   run: |
-      #     Xvfb :1 -screen 0 1024x768x16 &
-      #     export DISPLAY=:1
-      #     yarn coverage:ci > test_output.log 2>&1 || (grep -q 'ERROR: Coverage' test_output.log && echo "coverage_failed=true" >> $GITHUB_OUTPUT) || echo "test_failed=true" >> $GITHUB_OUTPUT
+      - name: Run Tests
+        id: run_tests
+        if: github.event.pull_request.user.login != 'dependabot[bot]'
+        run: |
+          Xvfb :1 -screen 0 1024x768x16 &
+          export DISPLAY=:1
+          yarn coverage:ci > test_output.log 2>&1 || (grep -q 'ERROR: Coverage' test_output.log && echo "coverage_failed=true" >> $GITHUB_OUTPUT) || echo "test_failed=true" >> $GITHUB_OUTPUT
 
-      # - name: Run Tests and Coverage (Exclude Encryption)
-      #   id: run_tests_exclude_encryption
-      #   if: github.event.pull_request.user.login == 'dependabot[bot]'
-      #   run: |
-      #     Xvfb :1 -screen 0 1024x768x16 &
-      #     export DISPLAY=:1
-      #     yarn coverage:ci:exclude-encryption > test_output.log 2>&1 || (grep -q 'ERROR: Coverage' test_output.log && echo "coverage_failed=true" >> $GITHUB_OUTPUT) || echo "test_failed=true" >> $GITHUB_OUTPUT
-      #   continue-on-error: true
+      - name: Run Tests and Coverage (Exclude Encryption)
+        id: run_tests_exclude_encryption
+        if: github.event.pull_request.user.login == 'dependabot[bot]'
+        run: |
+          Xvfb :1 -screen 0 1024x768x16 &
+          export DISPLAY=:1
+          yarn coverage:ci:exclude-encryption > test_output.log 2>&1 || (grep -q 'ERROR: Coverage' test_output.log && echo "coverage_failed=true" >> $GITHUB_OUTPUT) || echo "test_failed=true" >> $GITHUB_OUTPUT
+        continue-on-error: true
 
-      # - name: Post Coverage Comment
-      #   if: steps.run_tests.outputs.coverage_failed == 'true'
-      #   uses: actions/github-script@v6
-      #   with:
-      #     github-token: ${{ secrets.GITHUB_TOKEN }}
-      #     script: |
-      #       const fs = require('fs');
-      #       const log = fs.readFileSync('test_output.log', 'utf8');
-      #       const coverageErrors = log.split('\n').filter(line => line.includes('ERROR: Coverage'));
+      - name: Post Coverage Comment
+        if: steps.run_tests.outputs.coverage_failed == 'true'
+        uses: actions/github-script@v6
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const fs = require('fs');
+            const log = fs.readFileSync('test_output.log', 'utf8');
+            const coverageErrors = log.split('\n').filter(line => line.includes('ERROR: Coverage'));
 
-      #       const commentBody = `
-      #       ## :x: Coverage Thresholds Not Met
+            const commentBody = `
+            ## :x: Coverage Thresholds Not Met
 
-      #       The following coverage thresholds were not met:
+            The following coverage thresholds were not met:
 
-      #       \`\`\`
-      #       ${coverageErrors.join('\n')}
-      #       \`\`\`
+            \`\`\`
+            ${coverageErrors.join('\n')}
+            \`\`\`
 
-      #       Please review the coverage report and improve the tests to meet the thresholds.
-      #       `;
+            Please review the coverage report and improve the tests to meet the thresholds.
+            `;
 
-      #       github.rest.issues.createComment({
-      #         issue_number: context.issue.number,
-      #         owner: context.repo.owner,
-      #         repo: context.repo.repo,
-      #         body: commentBody
-      #       });
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: commentBody
+            });
 
       - name: Set up Decryption Jar and Datapacks
         if: github.event.pull_request.user.login != 'dependabot[bot]'
@@ -339,12 +339,6 @@ jobs:
           fi
           echo "Successfully downloaded and extracted datapacks folder to assets/datapacks."
 
-          echo "Contents of the jars directory (${{ github.workspace }}/server/assets/jars):"
-          find "${{ github.workspace }}/server/assets/jars" -type f || echo "Failed to list contents of jars directory"
-
-          echo "Contents of the datapacks directory (${{ github.workspace }}/server/assets/datapacks):"
-          find "${{ github.workspace }}/server/assets/datapacks" -type f || echo "Failed to list contents of datapacks directory"
-
       - name: e2e Tests
         if: github.event.pull_request.user.login != 'dependabot[bot]'
         id: e2e_tests
@@ -353,23 +347,23 @@ jobs:
           export DISPLAY=:1
           yarn test:charts:ci > e2e_output.log 2>&1 || echo "e2e_failed=true" >> $GITHUB_OUTPUT
 
-      # - name: Report Test Errors
-      #   if: steps.run_tests.outputs.test_failed == 'true'
-      #   uses: actions/github-script@v5
-      #   with:
-      #     script: |
-      #       const fs = require('fs');
-      #       const testLog = fs.readFileSync('test_output.log', 'utf8');
-      #       const prNumber = context.payload.pull_request?.number;
-      #       if (prNumber) {
-      #         const message = `🚨 Vitest tests have failed. Please check the test logs for more information.\n\n\`\`\`\n${testLog}\n\`\`\``;
-      #         github.rest.issues.createComment({
-      #           ...context.repo,
-      #           issue_number: prNumber,
-      #           body: message,
-      #         });
-      #       }
-      #     github-token: ${{ secrets.GITHUB_TOKEN }}
+      - name: Report Test Errors
+        if: steps.run_tests.outputs.test_failed == 'true'
+        uses: actions/github-script@v5
+        with:
+          script: |
+            const fs = require('fs');
+            const testLog = fs.readFileSync('test_output.log', 'utf8');
+            const prNumber = context.payload.pull_request?.number;
+            if (prNumber) {
+              const message = `🚨 Vitest tests have failed. Please check the test logs for more information.\n\n\`\`\`\n${testLog}\n\`\`\``;
+              github.rest.issues.createComment({
+                ...context.repo,
+                issue_number: prNumber,
+                body: message,
+              });
+            }
+          github-token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Report E2E Test Errors
         if: steps.e2e_tests.outputs.e2e_failed == 'true'
@@ -415,9 +409,15 @@ jobs:
             }
 
       - name: Check for any test failures
-        if: steps.e2e_tests.outputs.e2e_failed == 'true'
+        if: steps.run_tests.outputs.test_failed == 'true' || steps.run_tests.outputs.coverage_failed == 'true' || steps.e2e_tests.outputs.e2e_failed == 'true'
         run: |
-          if [ "${{ steps.e2e_tests.outputs.e2e_failed }}" = "true" ]; then
+          if [ "${{ steps.run_tests.outputs.test_failed }}" = "true" ]; then
+            echo "Unit/coverage tests failed."
+            exit 1
+          elif [ "${{ steps.run_tests.outputs.coverage_failed }}" = "true" ]; then
+            echo "Coverage threshold not met."
+            exit 2
+          elif [ "${{ steps.e2e_tests.outputs.e2e_failed }}" = "true" ]; then
             echo "E2E tests failed."
             exit 3
           fi
