datapacks from dropbox

diff --git a/.github/workflows/merge-pipeline.yml b/.github/workflows/merge-pipeline.yml
--- a/.github/workflows/merge-pipeline.yml
+++ b/.github/workflows/merge-pipeline.yml
@@ -202,8 +202,8 @@ jobs:
             exit 1
           fi
 
-      - name: Find and Download Decryption Jar from Dropbox
-        id: decrypt_step
+      - name: Set up supporting files for e2e tests
+        id: supporting_files
         run: |
           ACCESS_TOKEN=$(curl -s https://api.dropbox.com/oauth2/token -d refresh_token=${{ secrets.DROPBOX_REFRESH_TOKEN }} -d grant_type=refresh_token -d client_id=${{ secrets.DROPBOX_APP_KEY }} -d client_secret=${{ secrets.DROPBOX_APP_SECRET }} | jq -r '.access_token')
 
@@ -230,7 +230,6 @@ jobs:
           --header "Authorization: Bearer $ACCESS_TOKEN" \
           --header "Dropbox-API-Arg: {\"path\": \"$DECRYPTION_PATH\"}" \
           --output "${{ github.workspace }}/server/assets/jars/$DECRYPTION_NAME"
-
           DECRYPTION_JAR="${{ github.workspace }}/server/assets/jars/$DECRYPTION_NAME"
           if [ ! -f "$DECRYPTION_JAR" ]; then
             echo "Error: Failed to download decryption jar."
@@ -238,6 +237,27 @@ jobs:
           fi
           echo "Successfully downloaded decryption jar."
           echo "jar_path=$DECRYPTION_JAR" >> $GITHUB_OUTPUT
+
+            DATAPACKS_PATH=$(echo "$LIST_RESPONSE" | jq -r --arg DATA_PACKS_NAME "datapacks" '.entries[] | select(.name == $DATA_PACKS_NAME) | .path_lower')
+            if [ -z "$DATAPACKS_PATH" ]; then
+              echo "Error: Datapacks folder not found."
+              exit 1
+            fi
+
+            curl -s -X POST "https://content.dropboxapi.com/2/files/download_zip" \
+            --header "Authorization: Bearer $ACCESS_TOKEN" \
+            --header "Dropbox-API-Arg: {\"path\": \"$DATAPACKS_PATH\"}" \
+            --output "${{ github.workspace }}/datapacks.zip"
+
+            if [ ! -f "${{ github.workspace }}/datapacks.zip" ]; then
+              echo "Error: Failed to download datapacks folder."
+              exit 1
+            fi
+
+            unzip -q "${{ github.workspace }}/datapacks.zip" -d "${{ github.workspace }}/server/assets/datapacks"
+            rm "${{ github.workspace }}/datapacks.zip"
+
+            echo "Successfully downloaded and extracted datapacks folder to assets/datapacks."
 
       - name: Run Tests
         id: run_tests
