rename jar

diff --git a/.github/workflows/merge-pipeline.yml b/.github/workflows/merge-pipeline.yml
--- a/.github/workflows/merge-pipeline.yml
+++ b/.github/workflows/merge-pipeline.yml
@@ -206,9 +206,36 @@ jobs:
         id: run_tests
         if: github.event.pull_request.user.login != 'dependabot[bot]'
         run: |
+          if [ -f "${{ github.workspace }}/server/assets/jars/testUsageJar.jar" ]; then
+            echo "Jar file found."
+          else
+            echo "Jar file not found."
+            exit 1
+          fi
+
+          pr_jar=$(jq -r '.activeJar' ${{ github.workspace }}/server/assets/config.json | xargs basename)
+          if [ -z pr_jar ]; then
+            echo "Error: activeJar not found in config.json"
+            exit 1
+          fi
+          echo "Active JAR: $pr_jar"
+
+          mv ${{ github.workspace }}/server/assets/jars/testUsageJar.jar ${{ github.workspace }}/server/assets/jars/$pr_jar
+          echo "Renamed jar to $pr_jar"
+
           Xvfb :1 -screen 0 1024x768x16 &
           export DISPLAY=:1
           yarn coverage:ci > test_output.log 2>&1 || (grep -q 'ERROR: Coverage' test_output.log && echo "coverage_failed=true" >> $GITHUB_OUTPUT) || echo "test_failed=true" >> $GITHUB_OUTPUT
+
+          mv ${{ github.workspace }}/server/assets/jars/$CONFIG_JAR_NAME ${{ github.workspace }}/server/assets/jars/testUsageJar.jar
+          echo "Renamed jar back to testUsageJar.jar"
+          if [ -f "${{ github.workspace }}/server/assets/jars/testUsageJar.jar" ]; then
+            echo "Successfully renamed jar back to testUsageJar.jar."
+          else
+            echo "Failed to rename jar back to testUsageJar.jar."
+            exit 1
+          fi
+
         continue-on-error: true
 
       - name: Run Tests and Coverage (Exclude Encryption)
