no more help

diff --git a/.github/workflows/merge-pipeline.yml b/.github/workflows/merge-pipeline.yml
--- a/.github/workflows/merge-pipeline.yml
+++ b/.github/workflows/merge-pipeline.yml
@@ -237,51 +237,51 @@ jobs:
             exit 1
           fi
 
-      - name: Run Tests
-        id: run_tests
-        if: github.event.pull_request.user.login != 'dependabot[bot]'
-        run: |
-          Xvfb :1 -screen 0 1024x768x16 &
-          export DISPLAY=:1
-          yarn coverage:ci > test_output.log 2>&1 || (grep -q 'ERROR: Coverage' test_output.log && echo "coverage_failed=true" >> $GITHUB_OUTPUT) || echo "test_failed=true" >> $GITHUB_OUTPUT
+      # - name: Run Tests
+      #   id: run_tests
+      #   if: github.event.pull_request.user.login != 'dependabot[bot]'
+      #   run: |
+      #     Xvfb :1 -screen 0 1024x768x16 &
+      #     export DISPLAY=:1
+      #     yarn coverage:ci > test_output.log 2>&1 || (grep -q 'ERROR: Coverage' test_output.log && echo "coverage_failed=true" >> $GITHUB_OUTPUT) || echo "test_failed=true" >> $GITHUB_OUTPUT
 
-      - name: Run Tests and Coverage (Exclude Encryption)
-        id: run_tests_exclude_encryption
-        if: github.event.pull_request.user.login == 'dependabot[bot]'
-        run: |
-          Xvfb :1 -screen 0 1024x768x16 &
-          export DISPLAY=:1
-          yarn coverage:ci:exclude-encryption > test_output.log 2>&1 || (grep -q 'ERROR: Coverage' test_output.log && echo "coverage_failed=true" >> $GITHUB_OUTPUT) || echo "test_failed=true" >> $GITHUB_OUTPUT
-        continue-on-error: true
+      # - name: Run Tests and Coverage (Exclude Encryption)
+      #   id: run_tests_exclude_encryption
+      #   if: github.event.pull_request.user.login == 'dependabot[bot]'
+      #   run: |
+      #     Xvfb :1 -screen 0 1024x768x16 &
+      #     export DISPLAY=:1
+      #     yarn coverage:ci:exclude-encryption > test_output.log 2>&1 || (grep -q 'ERROR: Coverage' test_output.log && echo "coverage_failed=true" >> $GITHUB_OUTPUT) || echo "test_failed=true" >> $GITHUB_OUTPUT
+      #   continue-on-error: true
 
-      - name: Post Coverage Comment
-        if: steps.run_tests.outputs.coverage_failed == 'true'
-        uses: actions/github-script@v6
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const fs = require('fs');
-            const log = fs.readFileSync('test_output.log', 'utf8');
-            const coverageErrors = log.split('\n').filter(line => line.includes('ERROR: Coverage'));
+      # - name: Post Coverage Comment
+      #   if: steps.run_tests.outputs.coverage_failed == 'true'
+      #   uses: actions/github-script@v6
+      #   with:
+      #     github-token: ${{ secrets.GITHUB_TOKEN }}
+      #     script: |
+      #       const fs = require('fs');
+      #       const log = fs.readFileSync('test_output.log', 'utf8');
+      #       const coverageErrors = log.split('\n').filter(line => line.includes('ERROR: Coverage'));
 
-            const commentBody = `
-            ## :x: Coverage Thresholds Not Met
+      #       const commentBody = `
+      #       ## :x: Coverage Thresholds Not Met
 
-            The following coverage thresholds were not met:
+      #       The following coverage thresholds were not met:
 
-            \`\`\`
-            ${coverageErrors.join('\n')}
-            \`\`\`
+      #       \`\`\`
+      #       ${coverageErrors.join('\n')}
+      #       \`\`\`
 
-            Please review the coverage report and improve the tests to meet the thresholds.
-            `;
+      #       Please review the coverage report and improve the tests to meet the thresholds.
+      #       `;
 
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: commentBody
-            });
+      #       github.rest.issues.createComment({
+      #         issue_number: context.issue.number,
+      #         owner: context.repo.owner,
+      #         repo: context.repo.repo,
+      #         body: commentBody
+      #       });
 
       # - name: Set up Decryption Jar and Datapacks
       #   if: github.event.pull_request.user.login != 'dependabot[bot]'
@@ -348,26 +348,26 @@ jobs:
           yarn test:charts:ci > e2e_output.log 2>&1 || echo "e2e_failed=true" >> $GITHUB_OUTPUT
         env:
           DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
-          DROPBOX_APP_KEY:       ${{ secrets.DROPBOX_APP_KEY }}
-          DROPBOX_APP_SECRET:    ${{ secrets.DROPBOX_APP_SECRET }}
+          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
+          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
 
-      - name: Report Test Errors
-        if: steps.run_tests.outputs.test_failed == 'true'
-        uses: actions/github-script@v5
-        with:
-          script: |
-            const fs = require('fs');
-            const testLog = fs.readFileSync('test_output.log', 'utf8');
-            const prNumber = context.payload.pull_request?.number;
-            if (prNumber) {
-              const message = `🚨 Vitest tests have failed. Please check the test logs for more information.\n\n\`\`\`\n${testLog}\n\`\`\``;
-              github.rest.issues.createComment({
-                ...context.repo,
-                issue_number: prNumber,
-                body: message,
-              });
-            }
-          github-token: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Report Test Errors
+      #   if: steps.run_tests.outputs.test_failed == 'true'
+      #   uses: actions/github-script@v5
+      #   with:
+      #     script: |
+      #       const fs = require('fs');
+      #       const testLog = fs.readFileSync('test_output.log', 'utf8');
+      #       const prNumber = context.payload.pull_request?.number;
+      #       if (prNumber) {
+      #         const message = `🚨 Vitest tests have failed. Please check the test logs for more information.\n\n\`\`\`\n${testLog}\n\`\`\``;
+      #         github.rest.issues.createComment({
+      #           ...context.repo,
+      #           issue_number: prNumber,
+      #           body: message,
+      #         });
+      #       }
+      #     github-token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Report E2E Test Errors
         if: steps.e2e_tests.outputs.e2e_failed == 'true'
@@ -413,15 +413,9 @@ jobs:
             }
 
       - name: Check for any test failures
-        if: steps.run_tests.outputs.test_failed == 'true' || steps.run_tests.outputs.coverage_failed == 'true' || steps.e2e_tests.outputs.e2e_failed == 'true'
+        if:  steps.e2e_tests.outputs.e2e_failed == 'true'
         run: |
-          if [ "${{ steps.run_tests.outputs.test_failed }}" = "true" ]; then
-            echo "Unit/coverage tests failed."
-            exit 1
-          elif [ "${{ steps.run_tests.outputs.coverage_failed }}" = "true" ]; then
-            echo "Coverage threshold not met."
-            exit 2
-          elif [ "${{ steps.e2e_tests.outputs.e2e_failed }}" = "true" ]; then
+          if [ "${{ steps.e2e_tests.outputs.e2e_failed }}" = "true" ]; then
             echo "E2E tests failed."
             exit 3
           fi
