removed swap to testUsageJar.jar

diff --git a/.github/workflows/merge-pipeline.yml b/.github/workflows/merge-pipeline.yml
--- a/.github/workflows/merge-pipeline.yml
+++ b/.github/workflows/merge-pipeline.yml
@@ -299,20 +299,20 @@ jobs:
           export DISPLAY=:1
           yarn coverage:ci > test_output.log 2>&1 || (grep -q 'ERROR: Coverage' test_output.log && echo "coverage_failed=true" >> $GITHUB_OUTPUT) || echo "test_failed=true" >> $GITHUB_OUTPUT
 
-          pr_jar=${{ steps.move_jar.outputs.pr_jar }}
-          if [ -z "$pr_jar" ]; then
-            echo "Error: pr_jar is empty. Check config.json format."
-            exit 1
-          fi
+          # pr_jar=${{ steps.move_jar.outputs.pr_jar }}
+          # if [ -z "$pr_jar" ]; then
+          #   echo "Error: pr_jar is empty. Check config.json format."
+          #   exit 1
+          # fi
 
-          mv ${{ github.workspace }}/server/assets/jars/$pr_jar ${{ github.workspace }}/server/assets/jars/testUsageJar.jar
+          # mv ${{ github.workspace }}/server/assets/jars/$pr_jar ${{ github.workspace }}/server/assets/jars/testUsageJar.jar
 
-          if [ -f "${{ github.workspace }}/server/assets/jars/testUsageJar.jar" ]; then
-            echo "Successfully renamed jar back to testUsageJar.jar."
-          else
-            echo "Failed to rename jar back to testUsageJar.jar."
-            exit 1
-          fi
+          # if [ -f "${{ github.workspace }}/server/assets/jars/testUsageJar.jar" ]; then
+          #   echo "Successfully renamed jar back to testUsageJar.jar."
+          # else
+          #   echo "Failed to rename jar back to testUsageJar.jar."
+          #   exit 1
+          # fi
 
       - name: Run Tests and Coverage (Exclude Encryption)
         id: run_tests_exclude_encryption
