detailed report

diff --git a/.github/workflows/merge-pipeline.yml b/.github/workflows/merge-pipeline.yml
--- a/.github/workflows/merge-pipeline.yml
+++ b/.github/workflows/merge-pipeline.yml
@@ -410,7 +410,17 @@ jobs:
 
       - name: Check for any test failures
         if: steps.run_tests.outputs.test_failed == 'true' || steps.run_tests.outputs.coverage_failed == 'true' || steps.e2e_tests.outputs.e2e_failed == 'true'
-        run: exit 1
+        run: |
+          if [ "${{ steps.run_tests.outputs.test_failed }}" = "true" ]; then
+            echo "Unit/coverage tests failed."
+            exit 1
+          elif [ "${{ steps.run_tests.outputs.coverage_failed }}" = "true" ]; then
+            echo "Coverage threshold not met."
+            exit 2
+          elif [ "${{ steps.e2e_tests.outputs.e2e_failed }}" = "true" ]; then
+            echo "E2E tests failed."
+            exit 3
+          fi
 
       - name: Determine if Jar Upload is Necessary
         if: github.event.pull_request.user.login != 'dependabot[bot]'
