changed dropbox path

diff --git a/.github/workflows/merge-pipeline.yml b/.github/workflows/merge-pipeline.yml
--- a/.github/workflows/merge-pipeline.yml
+++ b/.github/workflows/merge-pipeline.yml
@@ -283,61 +283,61 @@ jobs:
               body: commentBody
             });
 
-      # - name: Set up Decryption Jar and Datapacks
-      #   if: github.event.pull_request.user.login != 'dependabot[bot]'
-      #   run: |
-      #     ACCESS_TOKEN=$(curl -s https://api.dropbox.com/oauth2/token -d refresh_token=${{ secrets.DROPBOX_REFRESH_TOKEN }} -d grant_type=refresh_token -d client_id=${{ secrets.DROPBOX_APP_KEY }} -d client_secret=${{ secrets.DROPBOX_APP_SECRET }} | jq -r '.access_token')
-      #     DECRYPTION_NAME=$(jq -r '.decryptionJar' server/assets/config.json | xargs basename)
-      #     if [ -z "$DECRYPTION_NAME" ]; then
-      #       echo "Error: decryptionJar not found in config.json"
-      #       exit 1
-      #     fi
-      #     DROPBOX_FOLDER_PATH="${{ secrets.DROPBOX_PATH }}"
+      - name: Set up Decryption Jar and Datapacks
+        if: github.event.pull_request.user.login != 'dependabot[bot]'
+        run: |
+          ACCESS_TOKEN=$(curl -s https://api.dropbox.com/oauth2/token -d refresh_token=${{ secrets.DROPBOX_REFRESH_TOKEN }} -d grant_type=refresh_token -d client_id=${{ secrets.DROPBOX_APP_KEY }} -d client_secret=${{ secrets.DROPBOX_APP_SECRET }} | jq -r '.access_token')
+          DECRYPTION_NAME=$(jq -r '.decryptionJar' server/assets/config.json | xargs basename)
+          if [ -z "$DECRYPTION_NAME" ]; then
+            echo "Error: decryptionJar not found in config.json"
+            exit 1
+          fi
+          DROPBOX_FOLDER_PATH="${{ secrets.DROPBOX_PATH }}"
 
-      #     LIST_RESPONSE=$(curl -s -X POST "https://api.dropboxapi.com/2/files/list_folder" \
-      #     --header "Authorization: Bearer $ACCESS_TOKEN" \
-      #     --header "Content-Type: application/json" \
-      #     --data "{\"path\": \"$DROPBOX_FOLDER_PATH\"}")
+          LIST_RESPONSE=$(curl -s -X POST "https://api.dropboxapi.com/2/files/list_folder" \
+          --header "Authorization: Bearer $ACCESS_TOKEN" \
+          --header "Content-Type: application/json" \
+          --data "{\"path\": \"$DROPBOX_FOLDER_PATH\"}")
 
-      #     DECRYPTION_PATH=$(echo "$LIST_RESPONSE" | jq -r --arg DECRYPTION_NAME "$DECRYPTION_NAME" '.entries[] | select(.name == $DECRYPTION_NAME) | .path_lower')
-      #     if [ -z "$DECRYPTION_PATH" ]; then
-      #       echo "Error: Decryption jar not found."
-      #       exit 1
-      #     fi
-      #     DATAPACKS_PATH=$(echo "$LIST_RESPONSE" | jq -r --arg DATA_PACKS_NAME "datapacks" '.entries[] | select(.name == $DATA_PACKS_NAME) | .path_lower')
-      #     if [ -z "$DATAPACKS_PATH" ]; then
-      #       echo "Error: Datapacks folder not found."
-      #       exit 1
-      #     fi
+          DECRYPTION_PATH=$(echo "$LIST_RESPONSE" | jq -r --arg DECRYPTION_NAME "$DECRYPTION_NAME" '.entries[] | select(.name == $DECRYPTION_NAME) | .path_lower')
+          if [ -z "$DECRYPTION_PATH" ]; then
+            echo "Error: Decryption jar not found."
+            exit 1
+          fi
+          DATAPACKS_PATH=$(echo "$LIST_RESPONSE" | jq -r --arg DATA_PACKS_NAME "datapacks" '.entries[] | select(.name == $DATA_PACKS_NAME) | .path_lower')
+          if [ -z "$DATAPACKS_PATH" ]; then
+            echo "Error: Datapacks folder not found."
+            exit 1
+          fi
 
-      #     curl -s -X POST "https://content.dropboxapi.com/2/files/download" \
-      #     --header "Authorization: Bearer $ACCESS_TOKEN" \
-      #     --header "Dropbox-API-Arg: {\"path\": \"$DECRYPTION_PATH\"}" \
-      #     --output "${{ github.workspace }}/server/assets/jars/$DECRYPTION_NAME"
+          curl -s -X POST "https://content.dropboxapi.com/2/files/download" \
+          --header "Authorization: Bearer $ACCESS_TOKEN" \
+          --header "Dropbox-API-Arg: {\"path\": \"$DECRYPTION_PATH\"}" \
+          --output "${{ github.workspace }}/server/assets/jars/$DECRYPTION_NAME"
 
-      #     DECRYPTION_JAR="${{ github.workspace }}/server/assets/jars/$DECRYPTION_NAME"
-      #     if [ ! -f "$DECRYPTION_JAR" ]; then
-      #       echo "Error: Failed to download decryption jar."
-      #       exit 1
-      #     fi
-      #     echo "Successfully downloaded decryption jar."
+          DECRYPTION_JAR="${{ github.workspace }}/server/assets/jars/$DECRYPTION_NAME"
+          if [ ! -f "$DECRYPTION_JAR" ]; then
+            echo "Error: Failed to download decryption jar."
+            exit 1
+          fi
+          echo "Successfully downloaded decryption jar."
 
-      #     curl -s -X POST "https://content.dropboxapi.com/2/files/download_zip" \
-      #     --header "Authorization: Bearer $ACCESS_TOKEN" \
-      #     --header "Dropbox-API-Arg: {\"path\": \"$DATAPACKS_PATH\"}" \
-      #     --output "${{ github.workspace }}/datapacks.zip"
+          curl -s -X POST "https://content.dropboxapi.com/2/files/download_zip" \
+          --header "Authorization: Bearer $ACCESS_TOKEN" \
+          --header "Dropbox-API-Arg: {\"path\": \"$DATAPACKS_PATH\"}" \
+          --output "${{ github.workspace }}/datapacks.zip"
 
-      #     if [ ! -f "${{ github.workspace }}/datapacks.zip" ]; then
-      #       echo "Error: Failed to download datapacks folder."
-      #       exit 1
-      #     fi
-      #     unzip -q "${{ github.workspace }}/datapacks.zip" -d "${{ github.workspace }}/server/assets"
-      #     rm "${{ github.workspace }}/datapacks.zip"
-      #     if [ ! -d "${{ github.workspace }}/server/assets/datapacks" ]; then
-      #       echo "Error: Failed to extract datapacks folder."
-      #       exit 1
-      #     fi
-      #     echo "Successfully downloaded and extracted datapacks folder to assets/datapacks."
+          if [ ! -f "${{ github.workspace }}/datapacks.zip" ]; then
+            echo "Error: Failed to download datapacks folder."
+            exit 1
+          fi
+          unzip -q "${{ github.workspace }}/datapacks.zip" -d "${{ github.workspace }}/server/assets"
+          rm "${{ github.workspace }}/datapacks.zip"
+          if [ ! -d "${{ github.workspace }}/server/assets/datapacks" ]; then
+            echo "Error: Failed to extract datapacks folder."
+            exit 1
+          fi
+          echo "Successfully downloaded and extracted datapacks folder to assets/datapacks."
 
       - name: e2e Tests
         if: github.event.pull_request.user.login != 'dependabot[bot]'
